# Generated by Django 3.1.7 on 2021-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('key_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='关键名')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('appellation', models.CharField(max_length=20, verbose_name='称号')),
                ('description', models.TextField(max_length=100, verbose_name='描述')),
                ('position', models.CharField(choices=[('MELEE', '近战位'), ('RANGED', '远程位')], max_length=10, verbose_name='部署位')),
                ('max_potential_level', models.IntegerField(verbose_name='最大潜能')),
                ('rarity', models.IntegerField(verbose_name='稀有度')),
                ('profession', models.CharField(max_length=10, verbose_name='职业')),
                ('trait', models.CharField(max_length=10, null=True, verbose_name='特性')),
            ],
        ),
    ]
