# Generated by Django 3.1.7 on 2021-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkillData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyData',
            fields=[
                ('Key', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='键值')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('life_point_reduce', models.IntegerField(null=True, verbose_name='')),
                ('range_radius', models.FloatField(null=True, verbose_name='')),
                ('talent_black_board', models.CharField(max_length=20, null=True, verbose_name='')),
                ('skills', models.CharField(max_length=30, null=True, verbose_name='')),
                ('spdata', models.CharField(max_length=30, null=True, verbose_name='')),
                ('max_hp', models.IntegerField(null=True, verbose_name='最大血量')),
                ('atk', models.IntegerField(null=True, verbose_name='攻击')),
                ('defd', models.IntegerField(null=True, verbose_name='防御')),
                ('mag_res', models.IntegerField(null=True, verbose_name='法抗')),
                ('cost', models.IntegerField(null=True, verbose_name='部署费用')),
                ('block_cnt', models.IntegerField(null=True, verbose_name='')),
                ('move_speed', models.FloatField(null=True, verbose_name='移动速度')),
                ('attack_speed', models.FloatField(null=True, verbose_name='攻速')),
                ('base_atk_time', models.FloatField(null=True, verbose_name='攻击间隔')),
                ('respqwn_time', models.IntegerField(null=True, verbose_name='')),
                ('hp_rec_pre_sec', models.FloatField(null=True, verbose_name='')),
                ('sp_rec_pre_sec', models.FloatField(null=True, verbose_name='')),
                ('max_deploy_cnt', models.IntegerField(null=True, verbose_name='')),
                ('mass_level', models.IntegerField(null=True, verbose_name='重量')),
                ('base_force_level', models.IntegerField(null=True, verbose_name='嘲讽等级')),
                ('stun_immune', models.BooleanField(verbose_name='')),
                ('silence_immune', models.BooleanField(verbose_name='')),
                ('sleep_immune', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
